# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0004_auto_20171113_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Done'), ('C', 'Cancel'), ('H', 'Handeling')], default='P', max_length=1),
        ),
    ]
